#!/bin/sh

source /system/sdcard/config/userscripts/camera_module

lock_file="/tmp/camera_motion_script.lock"
jpg_file="/tmp/camera_motion_script.jpg"

if [ -f ${lock_file} ]; then
    echo "camera_motion_script is running"
    exit 1
fi

touch ${lock_file}

/system/sdcard/bin/getimage > ${jpg_file}

/system/sdcard/bin/curl -i -X POST -H "Content-Type: multipart/form-data" -F "token=${TOKEN}" -F "pic=@${jpg_file}" $URL_MOTION

rm -rf ${jpg_file}
rm -rf ${lock_file}

