#!/bin/sh

source /system/sdcard/config/userscripts/camera_module

# Swap
if [ ! -f /system/sdcard/swapfile ]; then
    dd if=/dev/zero of=/system/sdcard/swapfile bs=1M count=64
    mkswap /system/sdcard/swapfile
fi 

swapon /system/sdcard/swapfile

night_off
/system/sdcard/controlscripts/rtsp-h264 stop
motion_detect_off

# Request camera's setting from server 
/system/sdcard/config/userscripts/camera_setup_script 

